---
title: "Project Home"
site: workflowr::wflow_site
# output:
#   workflowr::wflow_html:
#     toc: false
output:
  bookdown::html_document2:
    toc: true
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---

This is the website for the research project "Tracking Land-Use Change".

If you have cloned the project to a local computer this website is
rendered in the `docs` subdirectory of the project directory.

If you are using `workflowr` to publish the research website it will
also be rendered online to GitHub Pages.

This page acts as a table of contents for the website. There are links
to the web pages generated from the analysis notebooks and to the
rendered versions of manuscripts/documents/presentations.

------------------------------------------------------------------------

## [Project Workflow Status](m_00_status.html) {.unnumbered}

This notebook displays the computational status of the project, that is,
whether everything is up to date. Ironically, this is currently the only
notebook that must be run manually, so this notebook only displays the
status **when the notebook was last executed** and there is no
indication whether the project status has changed since then.

------------------------------------------------------------------------

# Overview documents {.unnumbered}

## [Proposal](proposal.html) {.unnumbered}

This notebook explains the central ideas behind the project.

## [Notes](notes.html) {.unnumbered}

This notebook is for keeping notes of any points that may be useful for
later project or manuscript development and which are not covered in the
analysis notebooks or at risk of getting lost in the notebooks.

## [Workflow management](workflow.html) {.unnumbered}

This project uses the [`targets`](https://wlandau.github.io/targets/)
and [`workflowr`](https://github.com/jdblischak/workflowr) packages for
managing the workflow of the project (making sure that the dependencies
between computational steps are satisfied). When this work was started
there were no easily found examples of using `targets` and `workflowr`
together. This notebook contains notes on the proposed workflow for
using `targets` and `workflowr`.

------------------------------------------------------------------------

# Publications {.unnumbered}

Links to rendered manuscripts and presentations will go here.

------------------------------------------------------------------------

# META Notebooks {.unnumbered}

These notebooks capture the analyses that were carried out to develop
the code of the core processing pipeline. They are organised as
side-chains to the core processing pipeline.

Typically, a meta notebook will analyse the data available at one stage
of the core pipeline, to guide the writing of the functions required to
get to the next stage of the core pipeline. These meta notebooks
generally conclude with the definition of a function that will be used
in the core pipeline.

There may be multiple notebooks all relating to different aspects of the
same stage of the core pipeline.

Sometimes the analyses are more diffuse - characterising the data in a
way that may be helpful for guiding the development of future core
stages, but not immediately resulting in the development of functions
for the core pipeline.

## 01 Ideas for Developments {.unnumbered}

Examines ideas for developing work, beyond what was dome in WP-A.

### [m_uqdata](m_uqdata.html) {.unnumbered}

Examines options for quantifying the uncertainty in the different input data sources.

### [m_lifetables](m_lifetables.html) {.unnumbered}

Explains the idea of using life tables from population modelling in the land-use change context.

## 02 Plots of Data Sets {.unnumbered}

Plots each data to sense-check the contents

### [m_CS_plot](m_CS_plot.html) {.unnumbered}

CS data plotted